/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "message_store.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
message_store_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		arguments2 register_1_arg;
		arguments2 unsubscribe_1_arg;
		arguments1 store_1_arg;
		arguments2 num_messages_1_arg;
		arguments2 get_message_1_arg;
		client set_status_connected_1_arg;
		arguments2 set_status_disconnected_1_arg;
		arguments2 get_status_1_arg;
		arguments2 get_reciever_info_1_arg;
		arguments2 get_all_messages_1_arg;
	} argument;
	union {
		int init_1_res;
		int register_1_res;
		int unsubscribe_1_res;
		int store_1_res;
		int num_messages_1_res;
		char *get_message_1_res;
		int set_status_connected_1_res;
		int set_status_disconnected_1_res;
		char get_status_1_res;
		client get_reciever_info_1_res;
		client_messages get_all_messages_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INIT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))init_1_svc;
		break;

	case REGISTER:
		_xdr_argument = (xdrproc_t) xdr_arguments2;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))register_1_svc;
		break;

	case UNSUBSCRIBE:
		_xdr_argument = (xdrproc_t) xdr_arguments2;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))unsubscribe_1_svc;
		break;

	case STORE:
		_xdr_argument = (xdrproc_t) xdr_arguments1;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))store_1_svc;
		break;

	case NUM_MESSAGES:
		_xdr_argument = (xdrproc_t) xdr_arguments2;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))num_messages_1_svc;
		break;

	case GET_MESSAGE:
		_xdr_argument = (xdrproc_t) xdr_arguments2;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (bool_t (*) (char *, void *,  struct svc_req *))get_message_1_svc;
		break;

	case set_status_connected:
		_xdr_argument = (xdrproc_t) xdr_client;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))set_status_connected_1_svc;
		break;

	case set_status_disconnected:
		_xdr_argument = (xdrproc_t) xdr_arguments2;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))set_status_disconnected_1_svc;
		break;

	case get_status:
		_xdr_argument = (xdrproc_t) xdr_arguments2;
		_xdr_result = (xdrproc_t) xdr_char;
		local = (bool_t (*) (char *, void *,  struct svc_req *))get_status_1_svc;
		break;

	case get_reciever_info:
		_xdr_argument = (xdrproc_t) xdr_arguments2;
		_xdr_result = (xdrproc_t) xdr_client;
		local = (bool_t (*) (char *, void *,  struct svc_req *))get_reciever_info_1_svc;
		break;

	case get_all_messages:
		_xdr_argument = (xdrproc_t) xdr_arguments2;
		_xdr_result = (xdrproc_t) xdr_client_messages;
		local = (bool_t (*) (char *, void *,  struct svc_req *))get_all_messages_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!message_store_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (message_store, message_storeVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, message_store, message_storeVER, message_store_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (message_store, message_storeVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, message_store, message_storeVER, message_store_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (message_store, message_storeVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
