/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "message_store.h"

bool_t
xdr_arguments1 (XDR *xdrs, arguments1 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->sender, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->recipient, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->message_identifier))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->message, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->file_name, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_arguments2 (XDR *xdrs, arguments2 *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->user, 30,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->message_identifier))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_pending_messages_rpc (XDR *xdrs, pending_messages_rpc *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->sender, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->receiver, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->message, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->id))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client_messages (XDR *xdrs, client_messages *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->list, 256,
		sizeof (pending_messages_rpc), (xdrproc_t) xdr_pending_messages_rpc))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client (XDR *xdrs, client *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->user, 128,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->client_port))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->sockaddr_in_sin_family))
				 return FALSE;
			 if (!xdr_u_short (xdrs, &objp->sockaddr_in_sin_port))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->client_port);
		IXDR_PUT_SHORT(buf, objp->sockaddr_in_sin_family);
		IXDR_PUT_U_SHORT(buf, objp->sockaddr_in_sin_port);
		}
		 if (!xdr_vector (xdrs, (char *)objp->sockaddr_in_sin_zerp, 8,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_u_long (xdrs, &objp->in_addr_s_addr))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->user, 128,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->client_port))
				 return FALSE;
			 if (!xdr_short (xdrs, &objp->sockaddr_in_sin_family))
				 return FALSE;
			 if (!xdr_u_short (xdrs, &objp->sockaddr_in_sin_port))
				 return FALSE;

		} else {
		objp->client_port = IXDR_GET_LONG(buf);
		objp->sockaddr_in_sin_family = IXDR_GET_SHORT(buf);
		objp->sockaddr_in_sin_port = IXDR_GET_U_SHORT(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->sockaddr_in_sin_zerp, 8,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_u_long (xdrs, &objp->in_addr_s_addr))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->user, 128,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->client_port))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->sockaddr_in_sin_family))
		 return FALSE;
	 if (!xdr_u_short (xdrs, &objp->sockaddr_in_sin_port))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->sockaddr_in_sin_zerp, 8,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->in_addr_s_addr))
		 return FALSE;
	return TRUE;
}
